### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by gielk** [neil-morrison44/homebridge-am43-blinds-bluez#4]
I don't know what to do.

![image](https://user-images.githubusercontent.com/24224715/183440838-5845d44a-2e2f-4f28-8e19-614361561d69.png)

it got stuck on this proces.

![image](https://user-images.githubusercontent.com/24224715/183442101-c9f4b4e7-4206-424d-8589-7b7e11dde0f3.png)

**Comment by gielk** [comment]
```
1330 timing reifyNode:node_modules/homebridge-am43-blinds-bluez/node_modules/node-gyp Completed in 38133ms
1331 timing reifyNode:node_modules/homebridge-plugin-update-check/node_modules/node-gyp Completed in 38138ms
1332 timing reifyNode:node_modules/homebridge-am43-blinds/node_modules/usb Completed in 38410ms
1333 timing reifyNode:node_modules/homebridge-am43-blinds-bluez/node_modules/node-ble Completed in 282212ms
1334 timing reify:unpack Completed in 282270ms
1335 timing reify:rollback:createSparse Completed in 7526ms
1336 timing reify:rollback:retireShallow Completed in 332ms
1337 timing command:install Completed in 315679ms
1338 verbose stack Error: process terminated
1338 verbose stack     at /opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:198:39
1338 verbose stack     at process.<anonymous> (/opt/homebridge/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)
1338 verbose stack     at process.emit (node:events:539:35)
1339 verbose cwd /var/lib/homebridge
1340 verbose Linux 5.15.32-v7+
1341 verbose node v16.16.0
1342 verbose npm  v8.11.0
1343 error process terminated
1344 error signal SIGTERM
1345 verbose exit 1
1346 timing npm Completed in 316422ms
1347 verbose unfinished npm timer reify 1659968723407
1348 verbose code 1
1349 error A complete log of this run can be found in:
1349 error     /home/pi/.npm/_logs/2022-08-08T14_25_22_683Z-debug-0.log
```

**Comment by neil-morrison44** [comment]
The error looks internal to npm, do other plugins install alright?

**Comment by RamSet** [comment]
+1

it fails to install on mine too. Other plugins install just fine …


Node.js Version | v16.16.0
Homebridge 1.5.0

**Comment by julioviegas** [comment]
same here

**Comment by Genestro** [comment]
Did anyone find a fix for this?

**Comment by gielk** [comment]
Unfortunately no, I moved to Homeassitant a little bit complicated at the start but when u got the hang of it so much more possibilities.
